'use strict';
function splitAddresses(value){return value.split(',').map(x=>x.trim()).filter(Boolean);}
function attachmentEditor(form,original){const items=original.map(x=>({...x}));const list=node('div');const draw=()=>{list.replaceChildren();for(const item of items)list.append(node('p',item.name+' · '+item.size+' 字节'),button('移除此附件',()=>{items.splice(items.indexOf(item),1);dirty=true;draw();note('附件列表已修改，请保存草稿。');}));};const label=node('label','添加附件（总计最多 5 MiB）'),input=node('input');input.type='file';label.append(input);input.onchange=()=>run(async()=>{const file=input.files[0];if(!file)return;if(file.size>5*1024*1024)throw Error('附件超过 5 MiB。');const encoded=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(',')[1]);r.onerror=reject;r.readAsDataURL(file);});const item=await api('/api/attachments',{name:file.name,base64:encoded});items.push(item);dirty=true;draw();note('附件已上传，请保存草稿以加入本次回复。');},input);form.append(label,list);draw();return items;}
function renderSending(t,box){const labels={preview:'待确认',confirmed:'已确认，尚未发送',sending:'发送中或等待中断核对',accepted:'SMTP 已接收（不代表最终投递或已读）',failed:'明确失败；可重新预览并确认后再尝试',unknown:'结果不明，不能自动重发'};const records=t.send_records||[];const blocked=records.some(r=>['accepted','sending','unknown'].includes(r.status));const area=node('section');area.append(node('h3','确认与发送'));
async function previewView(r){const view=node('div');view.append(node('h3','最终预览 · 草稿版本 '+r.content.version),node('p','发件人：'+r.content.from),node('p','收件人：'+r.content.to.join(', ')),node('p','抄送：'+(r.content.cc.join(', ')||'无')),node('p','密送：'+(r.content.bcc.join(', ')||'无')),node('p','主题：'+r.content.subject),node('pre',r.content.body));view.append(node('p',r.content.attachments.length?'附件：':'附件：无'));for(const a of r.content.attachments)view.append(node('p',a.name+' · '+a.size+' 字节'),node('small','SHA-256 '+a.sha256));const label=node('label'),check=node('input');check.type='checkbox';label.append(check,document.createTextNode('我已核对收件人、正文及附件，确认发送上述版本。'));view.append(label,button('确认上述版本并发送',async()=>{if(dirty)throw Error('存在未保存修改，请先保存并重新预览。');if(!check.checked)throw Error('请先勾选确认。');await api('/api/tasks/'+t.task_id+'/confirm-send',{send_id:r.id,fingerprint:r.fingerprint,confirmed:true});const sent=await api('/api/tasks/'+t.task_id+'/send',{send_id:r.id});await openTask(t.task_id,true);note(labels[sent.status]||sent.status);}));area.append(view);note('请核对最终预览，勾选后才可发送。');}
if(t.draft&&!blocked)area.append(button('生成最终发送预览',async()=>{if(dirty)throw Error('请先保存草稿修改。');const r=await api('/api/tasks/'+t.task_id+'/prepare-send',{version:t.draft.version});await previewView(r);}));for(const r of records){area.append(node('p',labels[r.status]||r.status),node('small','记录 '+r.id+' · '+r.message_id));const archived=node('details');archived.append(node('summary','查看此次冻结版本与结果'),node('pre',JSON.stringify({content:r.content,status:r.status,stage:r.stage,smtp_code:r.smtp_code,wire_sha256:r.wire_sha256},null,2)));area.append(archived);if(['unknown','accepted','sending'].includes(r.status))area.append(button('只读核对已发送目录',async()=>{const v=await api('/api/tasks/'+t.task_id+'/reconcile',{send_id:r.id});await openTask(t.task_id,true);note(v.sent_folder_check.matches.length?'找到相同 Message-ID 的副本；仍不代表最终投递。':'尚未找到副本，不能据此判定发送失败。');}));if(r.sent_folder_check)area.append(node('p',r.sent_folder_check.meaning));}box.append(area);}
const $=id=>document.getElementById(id);
let token=sessionStorage.getItem('mail-token')||'', current=null, dirty=false;
const statuses={new:'已建立',planning:'分析需求',preparing:'准备资料',drafting:'生成草稿',waiting_input:'等待补充',needs_review:'需要核对',failed:'执行失败',draft_ready:'草稿待审阅'};
function note(s){$('notice').textContent=s;}
function node(tag,value){const n=document.createElement(tag);if(value!==undefined)n.textContent=value;return n;}
function button(label,fn){const b=node('button',label);b.type='button';b.onclick=()=>run(fn,b);return b;}
async function api(path,data){const r=await fetch(path,{method:data===undefined?'GET':'POST',headers:{Authorization:'Bearer '+token,...(data===undefined?{}:{'Content-Type':'application/json'})},body:data===undefined?undefined:JSON.stringify(data)});const v=await r.json();if(!r.ok)throw Error(v.error||'操作失败');return v;}
async function run(fn,b){if(b)b.disabled=true;note('正在处理，可稍后刷新查看已保存进度。');try{await fn();}catch(e){note(e.message);}finally{if(b)b.disabled=false;}}
function renderQueue(status,items){const a=$('automation'),q=$('mail-queue');a.replaceChildren();q.replaceChildren();const s=status.scheduler||{},m=(status.monitor||{}).state||{};a.append(node('p','调度：'+(s.status||'未知')+'；最近成功：'+(s.last_success||'尚无')+'；最近扫描：'+(m.last_scan||'尚无')),node('p','采集积压：'+JSON.stringify((status.monitor||{}).current_generation_counts||{})+'；分类：'+JSON.stringify(status.classification_counts||{})));for(const item of items){const row=node('div');row.className='row';row.append(node('h3',item.subject||'无主题'),node('p',(item.from||'未知发件人')+' · UID '+item.uid),node('p','采集 '+item.collection_status+'；分类 '+(item.category||item.classification_status||'等待中')+(item.task_status?'；任务 '+item.task_status:'')));if(item.classification_reason)row.append(node('p','理由：'+item.classification_reason));if(item.task_id)row.append(button('打开关联任务',()=>openTask(item.task_id)));if(['classified','corrected'].includes(item.classification_status)){const form=node('form'),category=node('select');for(const [v,l] of [['reply_required','需要回复'],['no_reply','无需回复'],['user_review','需要判断']]){const o=node('option',l);o.value=v;o.selected=item.category===v;category.append(o);}const reason=node('input');reason.placeholder='本次纠正理由';reason.required=true;const extra=node('input');extra.placeholder='需要回复时填写目标；需要判断时填写问题';const submit=node('button','保存本次分类纠正');form.append(category,reason,extra,submit);form.onsubmit=e=>{e.preventDefault();run(async()=>{const data={validity:item.validity,uid:item.uid,category:category.value,reason:reason.value};if(category.value==='reply_required')data.suggested_goal=extra.value;if(category.value==='user_review')data.decision_question=extra.value;await api('/api/mail-queue/correct',data);await refresh();},submit);};row.append(form);}q.append(row);}}
async function refresh(){const [tasks,snapshots,automation,queue]=await Promise.all([api('/api/tasks'),api('/api/snapshots'),api('/api/automation'),api('/api/mail-queue')]);$('tasks').replaceChildren();for(const t of tasks){const row=node('div');row.className='row';row.append(button(t.subject||'无主题',()=>openTask(t.task_id)),node('small',t.delivery_status?({preview:'待确认发送',confirmed:'已确认待发送',sending:'发送中',unknown:'发送结果不明',failed:'发送失败',accepted:'SMTP 已接收'}[t.delivery_status]||t.delivery_status):(statuses[t.status]||t.status)));$('tasks').append(row);}for(const id of ['snapshot','history']){const old=$(id).value;$(id).replaceChildren();for(const s of snapshots){const o=node('option',s.subject+' · '+s.folder);o.value=s.id;$(id).append(o);}if(old)$(id).value=old;}renderQueue(automation,queue);$('workspace').hidden=false;$('login').hidden=true;note('列表已更新。');}
async function openTask(id,force=false){if(dirty&&!force&&!confirm('有尚未保存的草稿修改，是否放弃并打开任务？'))return;const t=await api('/api/tasks/'+id);current=t;dirty=false;render(t);note('任务已载入。');}
async function action(kind,data){if(dirty&&!confirm('有未保存的草稿修改，继续此操作将重新载入任务。是否继续？'))return;const r=await api('/api/tasks/'+current.task_id+'/'+kind,data);if(r.reply_feedback){note(r.reply_feedback.message);return;}await openTask(current.task_id,true);await refresh();note(r.reply_feedback?r.reply_feedback.message:r.error?r.error.message:'已保存。');}
function render(t){const box=$('detail');box.hidden=false;box.replaceChildren(node('h2',t.mail.Subject||'邮件任务'),node('p','状态：'+(statuses[t.status]||t.status)),node('p','目标：'+t.goal));if(t.error)box.append(node('p',t.error.message));for(const b of t.blockers)box.append(node('p','待核对：'+(typeof b==='string'?b:b.reason+'；解除方式：'+b.resolution)));box.append(button('重新准备 / 继续',async()=>{if(dirty&&!confirm('重新准备将放弃未保存的编辑，是否继续？'))return;await action('resume',{});}));
for(const u of (t.conversation_updates||[]).filter(x=>x.status==='pending')){const section=node('section');section.append(node('h3','发现新的相关往来'),node('p',(u.subject||'无主题')+' · '+(u.from||'未知发件人')+' · '+(u.date||'时间未知')),node('p','原草稿和用户编辑已保留；选择后旧发送预览均会失效。'),button('纳入新往来并重新准备',()=>action('conversation-update',{source_id:u.source_id,action:'include'})),button('标记为与本次回复无关',()=>action('conversation-update',{source_id:u.source_id,action:'ignore'})));box.append(section);}
box.append(button('按当前决定重新规划',()=>action('replan',{})));for(const n of t.notes||[])box.append(node('p','说明：'+n));
const original=node('details');original.append(node('summary','查看邮件与已提供往来'));for(const m of [t.mail,...t.history])original.append(node('p',m.From+' · '+m.Subject),node('pre',m.body));box.append(original);
for(const f of t.facts){box.append(node('p',f.question+' — '+(statuses[f.status]||f.status)));if(f.error){box.append(node('p','执行失败：'+f.error.code+' · '+f.error.message),button('重试此资料查询',()=>action('retry-child',{child_id:f.child_id})));}if(f.result){for(const n of f.result.notes||[])box.append(node('p','来源说明：'+n));for(const a of f.result.answers||[])box.append(node('p',a.text));for(const c of f.result.conflicts||[])box.append(node('p','需核对：'+c));}}
for(const r of t.requests||[]){const form=node('form');form.append(node('h3','补充资料'),node('p',r.missing.join('；')));const input=node('textarea');input.required=true;input.maxLength=12000;input.setAttribute('aria-label','资料补充内容');const scope=node('select');scope.setAttribute('aria-label','保存范围');for(const [v,l] of [['task','仅本次任务'],['personal','保存为长期个人资料']]){const o=node('option',l);o.value=v;scope.append(o);}const label=node('label');const check=node('input');check.type='checkbox';label.append(check,document.createTextNode('我已核对本次新旧事实冲突，确认采用补充值'));const submit=node('button','提交补充');form.append(input,scope,label,submit);form.onsubmit=e=>{e.preventDefault();run(()=>action('answer',{request_id:r.request_id,text:input.value,scope:scope.value,confirm_conflict:check.checked}),submit);};box.append(form);}
for(const d of t.decisions){const form=node('form');form.append(node('h3',d.question));const input=node('textarea');input.value=d.answer||'';input.required=true;input.maxLength=12000;input.setAttribute('aria-label',d.question);const b=node('button','保存本次决定');form.append(input,b);form.onsubmit=e=>{e.preventDefault();run(()=>action('decide',{decision_id:d.id,text:input.value}),b);};box.append(form);}
if(t.draft){const d=t.draft;box.append(node('h3','草稿 · 版本 '+d.version),node('p',t.freshness==='current'?'资料版本有效；修改内容仍需自行审阅。':'资料已变化，请先重新准备。'));const form=node('form');const fields={};for(const [key,title,value] of [['to','收件人（逗号分隔）',d.to.join(', ')],['cc','抄送（逗号分隔，可空）',(d.cc||[]).join(', ')],['bcc','密送（逗号分隔，可空）',(d.bcc||[]).join(', ')],['subject','主题',d.subject],['body','正文',d.body]]){const l=node('label',title),input=node(key==='body'?'textarea':'input');input.value=value;input.required=!['cc','bcc'].includes(key);input.id='draft-'+key;input.maxLength=key==='body'?16000:key==='subject'?500:5100;input.oninput=()=>{dirty=true;note('有未保存的草稿修改。');};fields[key]=input;l.append(input);form.append(l);}const attachments=attachmentEditor(form,d.attachments||[]);const save=node('button','保存草稿');save.disabled=t.status!=='draft_ready'||t.freshness!=='current';form.append(save);form.onsubmit=e=>{e.preventDefault();run(async()=>{await api('/api/tasks/'+t.task_id+'/edit',{version:d.version,body:fields.body.value,subject:fields.subject.value,to:splitAddresses(fields.to.value),cc:splitAddresses(fields.cc.value),bcc:splitAddresses(fields.bcc.value),attachments});await openTask(t.task_id,true);note('草稿已保存为新版本。');},save);};box.append(form,button('查看服务器最新版本（保留输入）',async()=>{const latest=await api('/api/tasks/'+t.task_id);const view=node('pre',latest.draft?JSON.stringify({version:latest.draft.version,to:latest.draft.to,subject:latest.draft.subject,body:latest.draft.body},null,2):'暂无草稿');box.append(view);note('当前输入未覆盖；复制需要保留的文字后可重新打开任务。');}));const history=node('details');history.append(node('summary','历史版本与来源'));for(const old of t.drafts)history.append(node('h3','版本 '+old.version+(old.editor==='user'?' · 用户修改':'')),node('pre',old.body));history.append(node('pre',JSON.stringify(d.sources,null,2)));box.append(history);}renderSending(t,box);}
$('login-form').onsubmit=e=>{e.preventDefault();token=$('token').value;run(async()=>{await refresh();sessionStorage.setItem('mail-token',token);},e.submitter);};
$('refresh').onclick=()=>run(refresh,$('refresh'));
$('scan').onclick=()=>run(async()=>{await api('/api/automation/scan',{});await refresh();note('单轮扫描与处理已完成。');},$('scan'));
$('pause').onclick=()=>run(async()=>{await api('/api/automation/pause',{});await refresh();note('自动处理已暂停。');},$('pause'));
$('resume').onclick=()=>run(async()=>{await api('/api/automation/resume',{});await refresh();note('自动处理已恢复。');},$('resume'));
$('logout').onclick=()=>{if(dirty&&!confirm('有未保存修改，仍然退出？'))return;sessionStorage.removeItem('mail-token');location.reload();};
$('create').onsubmit=e=>{e.preventDefault();run(async()=>{const t=await api('/api/tasks',{snapshot:$('snapshot').value,goal:$('goal').value,history:Array.from($('history').selectedOptions).map(o=>o.value)});await refresh();await openTask(t.task_id);},e.submitter);};
$('inbox-load').onclick=()=>run(async()=>{const mails=await api('/api/inbox');$('inbox').replaceChildren();for(const m of mails){const row=node('div');row.append(node('p',m.Subject+' · '+m.From),button('只读保存这封邮件',async()=>{const s=await api('/api/import',{uid:m.uid,uidvalidity:m.uidvalidity});await refresh();$('snapshot').value=s.id;note('邮件已保存，可填写目标开始准备。');}));$('inbox').append(row);}note('最近邮件已列出。');},$('inbox-load'));
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
if(token)run(refresh);
